name: gMultiWorld
version: 2.0.0g
main: spigot.mrtg.gmultiworld.main.MultiWorld
description: A plugin for core world managing
author: Kazuki

commands:
   world:
     description: The main gMultiWorld Command
     usage: /world